[toolchain]
[features]
resolution = true
[programs.devnet]
omnipitch_core = "6ps8ao7CVhacnRajvFXWTmkknsRnHfEbWmtQ3nDCdBkj"
[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
[scripts]
test = "yarn ts-mocha -p ./tsconfig.json tests/**/*.ts"
